"use server"

export interface Hourly {
    "location": {
        "name": "London",
        "region": "City of London, Greater London",
        "country": "United Kingdom",
        "lat": 51.52,
        "lon": -0.11,
        "tz_id": "Europe/London",
        "localtime_epoch": 1714523413,
        "localtime": "2024-05-01 1:30"
    },
    "current": {
        "last_updated_epoch": 1714522500,
        "last_updated": "2024-05-01 01:15",
        "temp_c": number,
        "temp_f": 51.8,
        "is_day": 0,
        "condition": {
            "text": "Clear",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 4.3,
        "wind_kph": 6.8,
        "wind_degree": 110,
        "wind_dir": "ESE",
        "pressure_mb": 1008.0,
        "pressure_in": 29.77,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 94,
        "cloud": 0,
        "feelslike_c": 10.5,
        "feelslike_f": 50.9,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 1.0,
        "gust_mph": 7.7,
        "gust_kph": 12.3
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2024-05-01",
                "date_epoch": 1714521600,
                "day": {
                    "maxtemp_c": 17.5,
                    "maxtemp_f": 63.5,
                    "mintemp_c": 9.6,
                    "mintemp_f": 49.4,
                    "avgtemp_c": 13.6,
                    "avgtemp_f": 56.5,
                    "maxwind_mph": 7.8,
                    "maxwind_kph": 12.6,
                    "totalprecip_mm": 1.94,
                    "totalprecip_in": 0.08,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 7.0,
                    "avgvis_miles": 4.0,
                    "avghumidity": 85,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 92,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "uv": 4.0
                },
                "astro": {
                    "sunrise": "05:32 AM",
                    "sunset": "08:24 PM",
                    "moonrise": "03:16 AM",
                    "moonset": "11:16 AM",
                    "moon_phase": "Last Quarter",
                    "moon_illumination": 55,
                    "is_moon_up": 0,
                    "is_sun_up": 0
                },
                "hour": [
                    {
                        "time_epoch": 1714518000,
                        "time": "2024-05-01 00:00",
                        "temp_c": 10.3,
                        "temp_f": 50.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.3,
                        "wind_kph": 6.8,
                        "wind_degree": 113,
                        "wind_dir": "ESE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.8,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 93,
                        "cloud": 24,
                        "feelslike_c": 9.7,
                        "feelslike_f": 49.4,
                        "windchill_c": 9.7,
                        "windchill_f": 49.4,
                        "heatindex_c": 10.3,
                        "heatindex_f": 50.6,
                        "dewpoint_c": 9.3,
                        "dewpoint_f": 48.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.9,
                        "gust_kph": 12.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714521600,
                        "time": "2024-05-01 01:00",
                        "temp_c": 11.0,
                        "temp_f": 51.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.3,
                        "wind_kph": 6.8,
                        "wind_degree": 110,
                        "wind_dir": "ESE",
                        "pressure_mb": 1008.0,
                        "pressure_in": 29.77,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 94,
                        "cloud": 0,
                        "feelslike_c": 9.6,
                        "feelslike_f": 49.2,
                        "windchill_c": 9.6,
                        "windchill_f": 49.2,
                        "heatindex_c": 10.2,
                        "heatindex_f": 50.3,
                        "dewpoint_c": 9.2,
                        "dewpoint_f": 48.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.7,
                        "gust_kph": 12.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714525200,
                        "time": "2024-05-01 02:00",
                        "temp_c": 9.8,
                        "temp_f": 49.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Mist",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                            "code": 1030
                        },
                        "wind_mph": 2.5,
                        "wind_kph": 4.0,
                        "wind_degree": 119,
                        "wind_dir": "ESE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.78,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 95,
                        "cloud": 17,
                        "feelslike_c": 9.9,
                        "feelslike_f": 49.9,
                        "windchill_c": 9.9,
                        "windchill_f": 49.9,
                        "heatindex_c": 9.8,
                        "heatindex_f": 49.7,
                        "dewpoint_c": 9.1,
                        "dewpoint_f": 48.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 4.8,
                        "gust_kph": 7.7,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714528800,
                        "time": "2024-05-01 03:00",
                        "temp_c": 9.6,
                        "temp_f": 49.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Mist",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                            "code": 1030
                        },
                        "wind_mph": 1.1,
                        "wind_kph": 1.8,
                        "wind_degree": 148,
                        "wind_dir": "SSE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.78,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 96,
                        "cloud": 30,
                        "feelslike_c": 9.6,
                        "feelslike_f": 49.2,
                        "windchill_c": 9.6,
                        "windchill_f": 49.2,
                        "heatindex_c": 9.6,
                        "heatindex_f": 49.2,
                        "dewpoint_c": 8.9,
                        "dewpoint_f": 48.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 2.2,
                        "gust_kph": 3.5,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714532400,
                        "time": "2024-05-01 04:00",
                        "temp_c": 9.6,
                        "temp_f": 49.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 0.4,
                        "wind_kph": 0.7,
                        "wind_degree": 183,
                        "wind_dir": "S",
                        "pressure_mb": 1008.0,
                        "pressure_in": 29.78,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 95,
                        "cloud": 26,
                        "feelslike_c": 9.6,
                        "feelslike_f": 49.4,
                        "windchill_c": 9.6,
                        "windchill_f": 49.4,
                        "heatindex_c": 9.6,
                        "heatindex_f": 49.4,
                        "dewpoint_c": 8.9,
                        "dewpoint_f": 48.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 0.8,
                        "gust_kph": 1.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714536000,
                        "time": "2024-05-01 05:00",
                        "temp_c": 9.4,
                        "temp_f": 48.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 0.2,
                        "wind_kph": 0.4,
                        "wind_degree": 248,
                        "wind_dir": "WSW",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.79,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 95,
                        "cloud": 36,
                        "feelslike_c": 9.4,
                        "feelslike_f": 48.9,
                        "windchill_c": 9.4,
                        "windchill_f": 48.9,
                        "heatindex_c": 9.4,
                        "heatindex_f": 48.9,
                        "dewpoint_c": 8.7,
                        "dewpoint_f": 47.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 0.4,
                        "gust_kph": 0.6,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714539600,
                        "time": "2024-05-01 06:00",
                        "temp_c": 10.3,
                        "temp_f": 50.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 0.4,
                        "wind_kph": 0.7,
                        "wind_degree": 305,
                        "wind_dir": "NW",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.8,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 92,
                        "cloud": 43,
                        "feelslike_c": 10.3,
                        "feelslike_f": 50.5,
                        "windchill_c": 10.3,
                        "windchill_f": 50.5,
                        "heatindex_c": 10.3,
                        "heatindex_f": 50.5,
                        "dewpoint_c": 9.0,
                        "dewpoint_f": 48.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 0.7,
                        "gust_kph": 1.1,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714543200,
                        "time": "2024-05-01 07:00",
                        "temp_c": 12.0,
                        "temp_f": 53.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 1.3,
                        "wind_kph": 2.2,
                        "wind_degree": 310,
                        "wind_dir": "NW",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.8,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 84,
                        "cloud": 38,
                        "feelslike_c": 12.0,
                        "feelslike_f": 53.5,
                        "windchill_c": 12.0,
                        "windchill_f": 53.5,
                        "heatindex_c": 12.0,
                        "heatindex_f": 53.5,
                        "dewpoint_c": 9.3,
                        "dewpoint_f": 48.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 1.7,
                        "gust_kph": 2.7,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714546800,
                        "time": "2024-05-01 08:00",
                        "temp_c": 13.5,
                        "temp_f": 56.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 2.2,
                        "wind_kph": 3.6,
                        "wind_degree": 304,
                        "wind_dir": "NW",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.8,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 78,
                        "cloud": 67,
                        "feelslike_c": 14.1,
                        "feelslike_f": 57.4,
                        "windchill_c": 14.1,
                        "windchill_f": 57.4,
                        "heatindex_c": 13.5,
                        "heatindex_f": 56.3,
                        "dewpoint_c": 9.7,
                        "dewpoint_f": 49.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 2.6,
                        "gust_kph": 4.1,
                        "uv": 3.0
                    },
                    {
                        "time_epoch": 1714550400,
                        "time": "2024-05-01 09:00",
                        "temp_c": 15.2,
                        "temp_f": 59.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 2.2,
                        "wind_kph": 3.6,
                        "wind_degree": 303,
                        "wind_dir": "WNW",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.79,
                        "precip_mm": 0.02,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 71,
                        "cloud": 74,
                        "feelslike_c": 15.2,
                        "feelslike_f": 59.4,
                        "windchill_c": 15.2,
                        "windchill_f": 59.4,
                        "heatindex_c": 15.2,
                        "heatindex_f": 59.4,
                        "dewpoint_c": 10.1,
                        "dewpoint_f": 50.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 84,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 2.6,
                        "gust_kph": 4.1,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714554000,
                        "time": "2024-05-01 10:00",
                        "temp_c": 16.5,
                        "temp_f": 61.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 2.9,
                        "wind_kph": 4.7,
                        "wind_degree": 330,
                        "wind_dir": "NNW",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.78,
                        "precip_mm": 0.03,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 66,
                        "cloud": 91,
                        "feelslike_c": 16.5,
                        "feelslike_f": 61.6,
                        "windchill_c": 16.5,
                        "windchill_f": 61.6,
                        "heatindex_c": 16.5,
                        "heatindex_f": 61.6,
                        "dewpoint_c": 10.2,
                        "dewpoint_f": 50.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 77,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.4,
                        "gust_kph": 5.4,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714557600,
                        "time": "2024-05-01 11:00",
                        "temp_c": 17.2,
                        "temp_f": 63.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 13,
                        "wind_dir": "NNE",
                        "pressure_mb": 1008.0,
                        "pressure_in": 29.76,
                        "precip_mm": 0.04,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 63,
                        "cloud": 99,
                        "feelslike_c": 17.2,
                        "feelslike_f": 63.0,
                        "windchill_c": 17.2,
                        "windchill_f": 63.0,
                        "heatindex_c": 17.2,
                        "heatindex_f": 63.0,
                        "dewpoint_c": 10.1,
                        "dewpoint_f": 50.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 89,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.4,
                        "gust_kph": 7.1,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714561200,
                        "time": "2024-05-01 12:00",
                        "temp_c": 17.7,
                        "temp_f": 63.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 33,
                        "wind_dir": "NNE",
                        "pressure_mb": 1008.0,
                        "pressure_in": 29.75,
                        "precip_mm": 0.23,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 63,
                        "cloud": 97,
                        "feelslike_c": 17.7,
                        "feelslike_f": 63.8,
                        "windchill_c": 17.7,
                        "windchill_f": 63.8,
                        "heatindex_c": 17.7,
                        "heatindex_f": 63.8,
                        "dewpoint_c": 10.5,
                        "dewpoint_f": 50.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 5.4,
                        "gust_kph": 8.7,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714564800,
                        "time": "2024-05-01 13:00",
                        "temp_c": 17.1,
                        "temp_f": 62.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 6.7,
                        "wind_kph": 10.8,
                        "wind_degree": 29,
                        "wind_dir": "NNE",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.74,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 67,
                        "cloud": 97,
                        "feelslike_c": 17.1,
                        "feelslike_f": 62.7,
                        "windchill_c": 17.1,
                        "windchill_f": 62.7,
                        "heatindex_c": 17.1,
                        "heatindex_f": 62.7,
                        "dewpoint_c": 10.9,
                        "dewpoint_f": 51.7,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.2,
                        "gust_kph": 13.2,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714568400,
                        "time": "2024-05-01 14:00",
                        "temp_c": 16.5,
                        "temp_f": 61.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                            "code": 1240
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 38,
                        "wind_dir": "NE",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.74,
                        "precip_mm": 0.19,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 73,
                        "cloud": 90,
                        "feelslike_c": 16.5,
                        "feelslike_f": 61.7,
                        "windchill_c": 16.5,
                        "windchill_f": 61.7,
                        "heatindex_c": 16.5,
                        "heatindex_f": 61.7,
                        "dewpoint_c": 11.7,
                        "dewpoint_f": 53.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.2,
                        "gust_kph": 13.2,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714572000,
                        "time": "2024-05-01 15:00",
                        "temp_c": 16.1,
                        "temp_f": 60.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                            "code": 1240
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 37,
                        "wind_dir": "NE",
                        "pressure_mb": 1007.0,
                        "pressure_in": 29.73,
                        "precip_mm": 0.32,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 79,
                        "cloud": 100,
                        "feelslike_c": 16.1,
                        "feelslike_f": 60.9,
                        "windchill_c": 16.1,
                        "windchill_f": 60.9,
                        "heatindex_c": 16.1,
                        "heatindex_f": 60.9,
                        "dewpoint_c": 12.5,
                        "dewpoint_f": 54.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.5,
                        "gust_kph": 12.1,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714575600,
                        "time": "2024-05-01 16:00",
                        "temp_c": 16.0,
                        "temp_f": 60.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                            "code": 1240
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 39,
                        "wind_dir": "NE",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.72,
                        "precip_mm": 0.16,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 82,
                        "cloud": 100,
                        "feelslike_c": 16.0,
                        "feelslike_f": 60.8,
                        "windchill_c": 16.0,
                        "windchill_f": 60.8,
                        "heatindex_c": 16.0,
                        "heatindex_f": 60.8,
                        "dewpoint_c": 13.0,
                        "dewpoint_f": 55.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.4,
                        "gust_kph": 11.9,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714579200,
                        "time": "2024-05-01 17:00",
                        "temp_c": 15.9,
                        "temp_f": 60.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 35,
                        "wind_dir": "NE",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.71,
                        "precip_mm": 0.07,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 83,
                        "cloud": 71,
                        "feelslike_c": 15.9,
                        "feelslike_f": 60.7,
                        "windchill_c": 15.9,
                        "windchill_f": 60.7,
                        "heatindex_c": 15.9,
                        "heatindex_f": 60.7,
                        "dewpoint_c": 13.1,
                        "dewpoint_f": 55.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.5,
                        "gust_kph": 10.5,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714582800,
                        "time": "2024-05-01 18:00",
                        "temp_c": 15.3,
                        "temp_f": 59.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 53,
                        "wind_dir": "NE",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.15,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 87,
                        "cloud": 81,
                        "feelslike_c": 15.4,
                        "feelslike_f": 59.6,
                        "windchill_c": 15.4,
                        "windchill_f": 59.6,
                        "heatindex_c": 15.4,
                        "heatindex_f": 59.6,
                        "dewpoint_c": 13.1,
                        "dewpoint_f": 55.7,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.6,
                        "gust_kph": 9.1,
                        "uv": 4.0
                    },
                    {
                        "time_epoch": 1714586400,
                        "time": "2024-05-01 19:00",
                        "temp_c": 14.1,
                        "temp_f": 57.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 3.6,
                        "wind_kph": 5.8,
                        "wind_degree": 58,
                        "wind_dir": "ENE",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.69,
                        "precip_mm": 0.04,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 91,
                        "cloud": 100,
                        "feelslike_c": 14.3,
                        "feelslike_f": 57.7,
                        "windchill_c": 14.3,
                        "windchill_f": 57.7,
                        "heatindex_c": 14.1,
                        "heatindex_f": 57.5,
                        "dewpoint_c": 12.7,
                        "dewpoint_f": 54.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 63,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.9,
                        "gust_kph": 9.5,
                        "uv": 3.0
                    },
                    {
                        "time_epoch": 1714590000,
                        "time": "2024-05-01 20:00",
                        "temp_c": 13.1,
                        "temp_f": 55.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Mist",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/143.png",
                            "code": 1030
                        },
                        "wind_mph": 4.5,
                        "wind_kph": 7.2,
                        "wind_degree": 67,
                        "wind_dir": "ENE",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.01,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 95,
                        "cloud": 100,
                        "feelslike_c": 12.9,
                        "feelslike_f": 55.1,
                        "windchill_c": 12.9,
                        "windchill_f": 55.1,
                        "heatindex_c": 13.2,
                        "heatindex_f": 55.7,
                        "dewpoint_c": 12.4,
                        "dewpoint_f": 54.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 72,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 7.6,
                        "gust_kph": 12.2,
                        "uv": 3.0
                    },
                    {
                        "time_epoch": 1714593600,
                        "time": "2024-05-01 21:00",
                        "temp_c": 13.4,
                        "temp_f": 56.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Mist",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                            "code": 1030
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 32,
                        "wind_dir": "NNE",
                        "pressure_mb": 1006.0,
                        "pressure_in": 29.7,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 94,
                        "cloud": 100,
                        "feelslike_c": 12.9,
                        "feelslike_f": 55.3,
                        "windchill_c": 12.9,
                        "windchill_f": 55.3,
                        "heatindex_c": 13.4,
                        "heatindex_f": 56.2,
                        "dewpoint_c": 12.6,
                        "dewpoint_f": 54.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 8.3,
                        "gust_kph": 13.4,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714597200,
                        "time": "2024-05-01 22:00",
                        "temp_c": 12.8,
                        "temp_f": 55.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Mist",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                            "code": 1030
                        },
                        "wind_mph": 7.4,
                        "wind_kph": 11.9,
                        "wind_degree": 13,
                        "wind_dir": "NNE",
                        "pressure_mb": 1005.0,
                        "pressure_in": 29.68,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 95,
                        "cloud": 88,
                        "feelslike_c": 11.7,
                        "feelslike_f": 53.0,
                        "windchill_c": 11.7,
                        "windchill_f": 53.0,
                        "heatindex_c": 12.8,
                        "heatindex_f": 55.0,
                        "dewpoint_c": 12.0,
                        "dewpoint_f": 53.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 11.1,
                        "gust_kph": 17.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1714600800,
                        "time": "2024-05-01 23:00",
                        "temp_c": 11.6,
                        "temp_f": 52.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Overcast ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                            "code": 1009
                        },
                        "wind_mph": 8.3,
                        "wind_kph": 13.3,
                        "wind_degree": 4,
                        "wind_dir": "N",
                        "pressure_mb": 1004.0,
                        "pressure_in": 29.66,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 95,
                        "cloud": 100,
                        "feelslike_c": 10.1,
                        "feelslike_f": 50.2,
                        "windchill_c": 10.1,
                        "windchill_f": 50.2,
                        "heatindex_c": 11.6,
                        "heatindex_f": 52.9,
                        "dewpoint_c": 10.9,
                        "dewpoint_f": 51.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.1,
                        "gust_kph": 19.4,
                        "uv": 1.0
                    }
                ]
            }
        ]
    }
}


export const getWeather = async (lat:string, lon:string) => {
    try  {
        const response = await fetch(`https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lon}&appid=884640013e4ecb518a41ae5b72a5c523&units=metric`)
        const data = await response.json()
        return data
    } catch(error) {
        console.log(error)
        return null
    }
}

export const getDaily = async (lat:string, lon:string, days:string) => {
    try  {
        const response = await fetch(`https://api.weatherapi.com/v1/forecast.json?key=${process.env.API_KEY}&q=${lat},${lon}&days=${days}&lang=es`)
        const data = await response.json()
        return data
    } catch(error) {
        console.log(error)
        return null
    }
}